
show_downloads: false
title: DIDACTS: Data-Intensive Discovery Accelerated by Computational Techniques for Science
description: Teaching Science to Machine Learning
theme: jekyll-theme-minimal
logo: didacts_logo_small.png
